language: bash

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

addons:
  apt:
    packages:
      - jq
      - xmlstarlet

before_install:
  - echo "${TRAVIS_OS_NAME}"
  - if [ "${TRAVIS_OS_NAME}" == 'osx' ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" == 'osx' ]; then brew install jq xmlstarlet; fi

script:
  - make test

notifications:
  email: false
  slack:
    rooms:
      - secure: "JZPstt5OU1ugY2Or+PwGOcEYElGQAtbt2ZqiFCI9diSx+v1+Z3kg+KrcftnDmytVtmIRB3xYHNu7vxqPkTKujieLMS1bv5VQhqcK0nw21SypuH/9PnS3M6otqTYl8ANNhnWBSoBxdseJ6Y09D+nYnDE52GpKL8YY1X2a6IR5R0tvJ6E38cYfXSH8TdXWqYbzaJXRbSXsmgwNW8J+93E49UqcMe4e5gQaD/xLihQfJGCNu2cBY8CFNG75dv/7xEmFyDO7it8qYTqoeU4k5u+1RBWqMjLcmhneTIKAwHF+5+5WsT4+VGmWjh2KzuDCyTmSRBSTYam4LIiX7OxLUTyjMd83VzPAPeJvNwPcbZTupojT4CH+vyH1VR3e8uyG+OUL1vYyJ46hPjQHbWpMTP9JrGwYf/N0Dcizjrha0ncQyjA43QiDQyS1bRzyybmyAK2Dv5fZ+2kQYOCGGnVXFNKwgpa8VNCIq7XnpuJR4TZa7gHzTtmOWeSnAzrCF8l9Z8hmWHzSYeSJClefBUZ8mQ9TCwHblcE0n069pxEG5eiDGAAIBMUTMEukAxlGQB26SMUJFzwwbnCDbNGNI8ncaLSJAuiCOa1+iFMenNtUbT0NndH/sot8N7aISrO5L4sV0t0JemuHl/tIGi7TGsENN+Brac8Lz8ou1O4+gh/yjuQSBjg="
